---
- name: install apache
  hosts: webservers
  tasks:
    - name: install apache
      yum:
        name: httpd
        state: latest
    - name: start apache
      service:
        name: httpd
        state: started
        enabled: true
    - name: create index.html file
      copy:
        content: welcome to my ansible website
        dest: /var/www/html/index.html
...
